---
- hosts: all
  vars_files:
  - env_variables_centos
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

  - name: Changing Selinux
    shell: |
      setenforce 0
      sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
      modprobe br_netfilter
  - name: Sync hosts file
    template: src=/etc/hosts dest=/etc/hosts

  - name: Changing iptables
    template: src=k8s.conf dest=/etc/sysctl.d/k8s.conf owner=root group=root
    register: k8s-iptables

  - name: Changing iptables
    template: src=k8s-module.conf dest=/etc/modules-load.d/k8s.conf owner=root group=root
    register: iptables_module

  - name: Sync the sysctl configuration
    command: sysctl --system
    when: k8s-iptables.changed

  - name: Sync the sysctl configuration
    command: sysctl --system
    when: iptables_module.changed
